config/routes.rb
Idealy::Application.routes.draw do
  resources :ideas

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  put '/ideas/:id/like' => 'ideas#like', via: 'put', as: :like
  put '/ideas/:id/follow' => 'ideas#follow', via: 'put', as: :follow
  put '/ideas/:id/contribute' => 'ideas#contribute', via: 'put', as: :contribute
  put '/ideas/:id/uncontribute' => 'ideas#uncontribute', via: 'put', as: :uncontribute

  resources :profile

  post '/ideas/create_update'=> 'ideas#create_update', via: 'post', as: :create_update
end

app/models/idea.rb
class Idea < ActiveRecord::Base
    acts_as_followable
    acts_as_votable

    belongs_to :user

    has_attached_file :photo, :styles => { :large => "900x900>", :medium => "300x300#", :thumb => "100x100#" } , :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
    validates_attachment :photo, :size => { :in => 0..5.megabytes }

    has_many :attachments
    accepts_nested_attributes_for :attachments

    has_many :contributors
    has_many :updates
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :like, :follow]
  before_filter :authenticate_user!

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    if user_signed_in?
      @idea.user = current_user
    end

    respond_to do |format|
      if @idea.save
        format.html { redirect_to ideas_path}
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea } #, notice: 'Idea was successfully updated.'
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def like
    @idea.vote :voter => current_user
    redirect_to ideas_path
  end

  def follow
    current_user.follow(@idea)
    redirect_to ideas_path
  end

  def create_update
      @idea = Idea.find(params["id"])
      @contributor = @idea.contributors.where(:user => current_user).first
      @idea.updates.create(:description => params["update"]["description"], :idea => @idea, :contributor => @contributor, :user => current_user)
      redirect_to :back
  end

  def contribute
    @idea = Idea.find(params[:id])
    if not @idea.contributors.exists?(:user => current_user)
        @contributor = @idea.contributors.create(:user => current_user, :idea => @idea)
    end
    respond_to do |format|
        format.html{ redirect_to :back }
        format.js
    end
  end

  def uncontribute
    @idea = Idea.find(params[:id])
    @contributor = @idea.contributors.where(:user => current_user).first
    if @idea.contributors.exists?(:user => current_user)
        @contributor.destroy
    end
    respond_to do |format|
        format.html{ redirect_to :back }
        format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:blurb, :problem, :solution, :description, :photo, attachments_attributes: [:attach])
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
    def render_idea(idea)
        idea.description
    end
end

app/views/ideas/_addContributorButton.html.erb
<%= link_to contribute_path(:idea => @idea.id), :class => "btn btn-default btn-block", :type => "button", :remote => true, :id => @idea.id, :method => :put, :'data-update-target' => 'contributors_section', :remote => true do %>
    Add Me As A Contributor!
<% end %>

app/views/ideas/_addUpdateBar.html.erb
<div class="update_bar">
    <%= form_for Update.new, :url => { :action => "create_update", :id => @idea.id }, :html => { :multipart => true } do |f| %>
      <div class="input-group input-group-lg">
          <%= f.text_field :description, :class => "form-control",  :autocomplete => "off", :placeholder => "Any Updates?", :id => "update_input_field" %>
          <div class="input-group-btn">
              <%= f.submit "post", :class => "btn btn-default", :id => "update_input_post_button", :tabindex => "-1" %>
          </div>
      </div>
    <% end %>
</div>

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/_removeContributorButton.html.erb
<%= link_to uncontribute_path(:idea => @idea.id), :class => "btn btn-default btn-block", :type => "button", :remote => true, :id => @idea.id, :method => :put, :'data-update-target' => 'contributors_section', :remote => true do %>
    Remove Me As A Contributor
<% end %>

app/views/ideas/contribute.js.erb
$("#contributor_list").append("<%= escape_javascript(render(@contributor)) %>");
$('#contributorButton').html('<%= escape_javascript(render 'removeContributorButton') %>');
$('.update_input').html('<%= escape_javascript(render 'addUpdateBar') %>');

app/views/ideas/edit.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/assets/idea.css.scss" />
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300' rel='stylesheet' type='text/css'>
</head>

<p id="notice"></p>

<%= form_for @idea, url: {action: "update"} do |f| %>
<div id="mainContainer">
    <div id="sideBarColumn">

            <div class="section coverPhoto">
            	<% if @idea.photo.exists? %>
                  <%= image_tag(@idea.photo.url(:medium))%>
                <% else %>
                  <%= image_tag("default_pro_pic.jpg") %>
                <% end %>
                <%= f.file_field :photo, id: "cover-photo-file-field" %>
                <div id="edit-cover-photo-wrapper">
                    <%= image_tag "edit.png", id: "edit-cover-photo"%>
                </div>
            </div>
        <div class="section contributors", id="contributors_section">
            <div class="contributor">
                <h1> Creator </h1>
                <hr>
                <%= link_to profile_path(@idea.user_id), :class => "contributor-profile-link" do %><%end%>
                <div class="contributorImg">
                    <% if @idea.user.avatar.exists? %>
                        <%= link_to image_tag(@idea.user.avatar.url(:medium)), profile_path(@idea.user_id) %>
                    <% else %>
                        <%= link_to image_tag("default_pro_pic.jpg"), profile_path(@idea.user_id)%>
                    <% end %>
                </div>
                <div class="contributorContent">
                    <p><%= @idea.user.name %></p>
                </div>
            </div>
            <div id="contributor_list">
                <h1> Contributors </h1>
                <hr>
                <%= render :partial => @idea.contributors %>
            </div>
            <% if (@idea.user_id != current_user.id) %>
            <div class="contributorButton", id="contributorButton">
                <% if current_user.contributors.select {|o| @idea.contributors.include? o}.size == 0 %>
                    <%= render 'addContributorButton' %>
                <% else %>
                    <%= render 'removeContributorButton' %>
                <% end %>
            </div>
            <% end %>
        </div>

        <div id="edit-idea-done-wrapper">
            <%= f.submit "Done Editing", id: "edit-idea-done-button", :class => "btn btn-default btn-block" %>
        </div>
    </div>
    <div id="contentColumn">
        <div class="section blurb">
           <%= f.text_field :blurb, id: "edit-blurb", placeholder: "Quick blurb...", maxlength: "140", autocomplete: "off" %>
        </div>

        <div class="section description">
            <p class="question">
                What is the problem?
            </p>
            <p class="answer">
                <%= f.text_area :problem, id: "edit-problem", placeholder: "What is the problem?", autocomplete: "off" %>
            </p>
            <p class="question">
                How do you want to solve it?
            </p>
            <p class="answer">
                <%= f.text_area :solution, id: "edit-solution", placeholder: "How do you want to solve it?", autocomplete: "off" %>
            </p>
        </div>


        <% if @idea.attachments.count != 0 %>
            <div class="section media">
                <%= file_field_tag('idea_attachments_attach', id: "edit-media-file-field", multiple: true, name: "idea[attachments_attributes][][attach]") %>
                <div id="edit-media-wrapper">
                    <%= image_tag "edit.png", id: "edit-media"%>
                </div>
                <div class="flexslider">
                    <ul class="slides">
                        <% @idea.attachments.each do |img| %>
                            <li><%= link_to image_tag(img.attach.url(:medium)), img.attach.url(), :data => {:imagelightbox=>"a"} %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
            <script>
                $('a').imageLightbox();
            </script>
        <% else %>
            <div class="section no-media">
                <p>How will it look?  Add photos or sketches...</p>
                <%= file_field_tag('idea_attachments_attach', id: "add-media-button-file-field", multiple: true, name: "idea[attachments_attributes][][attach]") %>
                <div id="add-media-button-wrapper">
                    <%= image_tag "edit.png", id: "add-media-button"%>
                </div>
            </div >
        <% end %>

        <div class="section comments">
            <div id="disqus_wrapper">
              <div id="disqus_thread"></div>
              <script type="text/javascript">
                  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                  var disqus_shortname = 'scratchpaper'; // required: replace example with your forum shortname

                  /* * * DON'T EDIT BELOW THIS LINE * * */
                  (function() {
                      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                  })();
              </script>
              <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
              <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
            </div>
        </div>


    </div>

    <div id="updatesColumn">
        <div class="update_input">
            <% if current_user.contributors.select {|o| @idea.contributors.include? o}.size != 0 %>
                <%= render 'addUpdateBar' %>
            <% end %>
        </div>
        <div class="section updates">
            <div class="updates title">
                Updates
            </div>
            <div class="updates ticks">
                <% if @idea.updates.count != 0 %>
                    <%= render :partial => @idea.updates.reverse %>
                <% else %>
                    <hr>
                    <div class="updates tick">
                       Nothing yet, check back soon!
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="/assets/show.js" ></script>
</div>

<% end %>

</div>

<p id="notice"><%= notice %></p>

app/views/ideas/index.html.erb
<head>
    <link rel="stylesheet" type="text/css" href="/assets/ideas.css.scss" />
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300' rel='stylesheet' type='text/css'>
</head>

<body>


  <div id="wrapper">
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
        <div id="newIdea">
    <div class="row">
      <div class="col-md-12">
          <%= form_for Idea.new, :url => { :action => "create" }, :html => { :multipart => true } do |f| %>
            <div class="input-group input-group-lg">
              <span class="input-group-addon" id="idea-countdown">140</span>
              <%= f.text_field :blurb, :class => "form-control",  :autocomplete => "off", :placeholder => "What's your latest idea?", :maxlength => 140 %>
              <div class="input-group-btn">
                <!-- Button and dropdown menu -->
                <%= f.submit "post", :class => "btn btn-default", :id => "new-idea-post-button", :tabindex => "-1" %>
                <button type="button" id="new-idea-dropdown" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu pull-right">
                  <li><a class="btn-default btn-file">Attach a photo<%= f.file_field :photo %></a></li>
                  <li><a class="btn-default btn-file">Add more photos!<%= file_field_tag('idea_attachments_attach', multiple: true, name: "idea[attachments_attributes][][attach]") %></a></li>
                  <li><a href="#">Add a full description</a></li>
                  <!--<li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li> -->
                </ul>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
      <!-- make sure this only fetches necessary fields for each idea rather than all ideas and selecting fields after -->
      <div id="all-ideas">
      <% @ideas.reverse.each do |idea| %>
        <% if idea.photo.exists? %>
          <% photoExists = true %>
          <div class="item w2">
          <%= link_to idea, :class => "ideaLink w2" do %><%end%>
        <% else %>
          <div class="item">
          <%= link_to idea, :class => "ideaLink" do %><%end%>
        <% end %>
            <% if photoExists %>
              <%= image_tag(idea.photo.url(:medium), :class => "img-container")%>
            <% end %>
            <% if photoExists %>
              <p class="pw2">
            <% else %>
              <p>
            <% end %>
              <%= idea.blurb %>
            <p>

            <% if photoExists %>
              <div class="item-buttons-w2">
            <% else %>
              <div class="item-buttons">
            <% end %>

              <%= link_to follow_path(idea), :class => "follow-button", :remote => true, :id => idea.id, :method => :put do %>
                <%= image_tag "icon_18944.png" %>
              <% end %>
              <div class="follow-count">
                <%= idea.followers_count %>
              </div>

              <%= link_to like_path(idea) , :class => "like-button", :remote => true, :id => idea.id, :method => :put do %>
                  <%= image_tag "icon_19367.png" %>
              <% end %>
              <div class="like-count">
                <%= idea.votes.size %>
              </div>


            </div>
          </div>
      <%end%>
    </div>
  </div>
</div>

</body>

app/views/ideas/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300' rel='stylesheet' type='text/css'>

<div id="new-idea">
 <!--  <h3>New idea</h3> -->
  <%= form_for @idea, url: {action: "create"}, id: "new" do |f| %>
<!--       <div id="new-idea-cover-photo">
        <%= image_tag "default_pro_pic.jpg", :id => "add-cover-photo-img" %>
      </div> -->

<!--       <div id="new-idea-buttons">
        <div class="new-idea-button left">
          <%= f.file_field :photo, id: "cover-photo-file-field" %>
        </div>
        <div class="new-idea-button right">
        </div>
      </div>  -->

      <%= f.text_field :blurb, id: "edit-blurb", placeholder: "Quick blurb...", maxlength: "140", autocomplete: "off" %>

      <%= f.text_area :problem, id: "edit-problem", placeholder: "What is the problem?", autocomplete: "off" %>

      <%= f.text_area :solution, id: "edit-solution", placeholder: "How do you want to solve it?", autocomplete: "off" %>

      <div id="new-idea-submit-wrapper">
        <%= f.submit "Done", id: "edit-idea-done-button" %>
      </div>
  <% end %>
</div>

app/views/ideas/show.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/assets/idea.css.scss" />
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300' rel='stylesheet' type='text/css'>
</head>

<p id="notice"><%= notice %></p>

<div id="mainContainer">
    <div id="sideBarColumn">
        <% if @idea.photo.exists? %>
            <div class="section coverPhoto">
                  <%= image_tag(@idea.photo.url(:medium))%>
                  <!--<%= link_to image_tag(@idea.photo.url(:medium)), @idea.photo.url() , :data => {:imagelightbox => "a"}%> -->
            </div>
        <% end %>
        <div class="section contributors", id="contributors_section">
            <div class="contributor">
                <h1> Creator </h1>
                <hr>
                <%= link_to profile_path(@idea.user_id), :class => "contributor-profile-link" do %><%end%>
                <div class="contributorImg">
                    <% if @idea.user.avatar.exists? %>
                        <%= link_to image_tag(@idea.user.avatar.url(:medium)), profile_path(@idea.user_id) %>
                    <% else %>
                        <%= link_to image_tag("default_pro_pic.jpg"), profile_path(@idea.user_id)%>
                    <% end %>
                </div>
                <div class="contributorContent">
                    <p><%= @idea.user.name %></p>
                </div>
            </div>
            <div id="contributor_list">
                <h1> Contributors </h1>
                <hr>
                <%= render :partial => @idea.contributors %>
            </div>
            <% if (@idea.user_id != current_user.id) %>
            <div class="contributorButton", id="contributorButton">
                <% if current_user.contributors.select {|o| @idea.contributors.include? o}.size == 0 %>
                    <%= render 'addContributorButton' %>
                <% else %>
                    <%= render 'removeContributorButton' %>
                <% end %>
            </div>
            <% end %>
        </div>

        <% if (@idea.user_id == current_user.id) %>
            <%= link_to edit_idea_path(:idea => @idea.id), :id => "edit-idea-button", :class => "btn btn-default btn-block", :type => "button" do %>Edit Idea<% end %>
        <% end %>
    </div>
    <div id="contentColumn">
        <div class="section blurb">
            "<%= @idea.blurb %>"
        </div>

        <% if (@idea.problem && @idea.problem.length != 0) || (@idea.solution && @idea.problem.length != 0)%>
            <div class="section description">
                <% if @idea.problem && @idea.problem.length != 0 %>
                <p class="question">
                    What is the problem?
                </p>
                <p class="answer">
                    <%= @idea.problem %>
                </p>
                <% end %>
                <% if @idea.solution && @idea.solution.length != 0%>
                <p class="question">
                    How do you want to solve it?
                </p>
                <p class="answer">
                    <%= @idea.solution %>
                </p>
                <% end %>
            </div>
        <% end %>


        <% if @idea.attachments.count != 0 %>
            <div class="section media">
                <div class="flexslider">
                    <ul class="slides">
                        <% @idea.attachments.each do |img| %>
                            <li><%= link_to image_tag(img.attach.url(:medium)), img.attach.url(), :data => {:imagelightbox=>"a"} %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
            <script>
                $('a').imageLightbox();
            </script>
        <% end %>

        <div class="section comments">
            <div id="disqus_wrapper">
              <div id="disqus_thread"></div>
              <script type="text/javascript">
                  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                  var disqus_shortname = 'scratchpaperdev'; // required: replace example with your forum shortname

                  /* * * DON'T EDIT BELOW THIS LINE * * */
                  (function() {
                      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                  })();
              </script>
              <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
              <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
            </div>
        </div>
    </div>
    <div id="updatesColumn">
        <div class="update_input">
            <% if current_user.contributors.select {|o| @idea.contributors.include? o}.size != 0 %>
                <%= render 'addUpdateBar' %>
            <% end %>
        </div>
        <div class="section updates">
            <div class="updates title">
                Updates
            </div>
            <div class="updates ticks">
                <% if @idea.updates.count != 0 %>
                    <%= render :partial => @idea.updates.reverse %>
                <% else %>
                    <hr>
                    <div class="updates tick">
                       Nothing yet, check back soon!
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/assets/show.js" ></script>
</div>

app/views/ideas/uncontribute.js.erb
$('#contributor_<%= @contributor.id %>').remove();
$('#contributorButton').html('<%= escape_javascript(render 'addContributorButton') %>');
$('.update_input').empty();