config/routes.rb
Idealy::Application.routes.draw do
  resources :ideas

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  put '/ideas/:id/like' => 'ideas#like', via: 'put', as: :like
  put '/ideas/:id/follow' => 'ideas#follow', via: 'put', as: :follow
  put '/ideas/:id/contribute' => 'ideas#contribute', via: 'put', as: :contribute
  put '/ideas/:id/uncontribute' => 'ideas#uncontribute', via: 'put', as: :uncontribute

  resources :profile

  post '/ideas/create_update'=> 'ideas#create_update', via: 'post', as: :create_update
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ScratchPaper', ideas_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit account', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
            </ul>
          </li>
        </ul>
        <p class="navbar-text navbar-right">
          <% if current_user.avatar.exists? %>
              <%= image_tag(current_user.avatar.url(:thumb), :class => "avatar") %>
          <% else %>
              <%= image_tag("default_pro_pic.jpg", :class => "avatar") %>
          <% end %>
          <%= link_to current_user.name, profile_index_path, :class => "navbar-link" %>
        </p>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if !user_signed_in? %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="/assets/framework_and_overrides.css.scss" />
    <link rel="stylesheet" type="text/css" href="/assets/home.css.scss" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ScratchPaper" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ScratchPaper" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
       <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>